# Copyright (C) 2022 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/mt8127-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/mt8127-common/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/amazon/mt8127-common/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/amazon/mt8127-common/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/amazon/mt8127-common/proprietary/bin/aal:system/bin/aal \
    vendor/amazon/mt8127-common/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/amazon/mt8127-common/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/amazon/mt8127-common/proprietary/bin/amzn_dha_hmac:system/bin/amzn_dha_hmac \
    vendor/amazon/mt8127-common/proprietary/bin/amzn_dha_tool:system/bin/amzn_dha_tool \
    vendor/amazon/mt8127-common/proprietary/bin/amzn_drmprov_check:system/bin/amzn_drmprov_check \
    vendor/amazon/mt8127-common/proprietary/bin/amzn_drmprov_tool:system/bin/amzn_drmprov_tool \
    vendor/amazon/mt8127-common/proprietary/bin/atci_service:system/bin/atci_service \
    vendor/amazon/mt8127-common/proprietary/bin/atcid:system/bin/atcid \
    vendor/amazon/mt8127-common/proprietary/bin/audiocli:system/bin/audiocli \
    vendor/amazon/mt8127-common/proprietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/amazon/mt8127-common/proprietary/bin/auto_shutdown.sh:system/bin/auto_shutdown.sh \
    vendor/amazon/mt8127-common/proprietary/bin/autobt:system/bin/autobt \
    vendor/amazon/mt8127-common/proprietary/bin/devicetype_service:system/bin/devicetype_service \
    vendor/amazon/mt8127-common/proprietary/bin/display:system/bin/display \
    vendor/amazon/mt8127-common/proprietary/bin/dump-ramdump.sh:system/bin/dump-ramdump.sh \
    vendor/amazon/mt8127-common/proprietary/bin/ext4_resize:system/bin/ext4_resize \
    vendor/amazon/mt8127-common/proprietary/bin/idme:system/bin/idme \
    vendor/amazon/mt8127-common/proprietary/bin/kdestroy:system/bin/kdestroy \
    vendor/amazon/mt8127-common/proprietary/bin/kinit:system/bin/kinit \
    vendor/amazon/mt8127-common/proprietary/bin/kisd:system/bin/kisd \
    vendor/amazon/mt8127-common/proprietary/bin/klist:system/bin/klist \
    vendor/amazon/mt8127-common/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/amazon/mt8127-common/proprietary/bin/kswitch:system/bin/kswitch \
    vendor/amazon/mt8127-common/proprietary/bin/kvno:system/bin/kvno \
    vendor/amazon/mt8127-common/proprietary/bin/meta_tst:system/bin/meta_tst \
    vendor/amazon/mt8127-common/proprietary/bin/mmp:system/bin/mmp \
    vendor/amazon/mt8127-common/proprietary/bin/msensord:system/bin/msensord \
    vendor/amazon/mt8127-common/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/amazon/mt8127-common/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/amazon/mt8127-common/proprietary/bin/pq:system/bin/pq \
    vendor/amazon/mt8127-common/proprietary/bin/recovery_reporter:system/bin/recovery_reporter \
    vendor/amazon/mt8127-common/proprietary/bin/rpmb_svc:system/bin/rpmb_svc \
    vendor/amazon/mt8127-common/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/amazon/mt8127-common/proprietary/bin/thermald:system/bin/thermald \
    vendor/amazon/mt8127-common/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/amazon/mt8127-common/proprietary/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
    vendor/amazon/mt8127-common/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/amazon/mt8127-common/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
    vendor/amazon/mt8127-common/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/amazon/mt8127-common/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/amazon/mt8127-common/proprietary/etc/firmware/ROMv2_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_patch_1_0_hdr.bin \
    vendor/amazon/mt8127-common/proprietary/etc/firmware/ROMv2_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_patch_1_1_hdr.bin \
    vendor/amazon/mt8127-common/proprietary/etc/firmware/WIFI_RAM_CODE_8127:system/etc/firmware/WIFI_RAM_CODE_8127 \
    vendor/amazon/mt8127-common/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/amazon/mt8127-common/proprietary/etc/monitoring.conf:system/etc/monitoring.conf \
    vendor/amazon/mt8127-common/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/amazon/mt8127-common/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/amazon/mt8127-common/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/amazon/mt8127-common/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/amazon/mt8127-common/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/amazon/mt8127-common/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/audio.primary.mt8127.so:system/lib/hw/audio.primary.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/camera.mt8127.so:system/lib/hw/camera.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/gralloc.mt8127.so:system/lib/hw/gralloc.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/hwcomposer.mt8127.so:system/lib/hw/hwcomposer.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/keystore.mt8127.so:system/lib/hw/keystore.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/memtrack.mt8127.so:system/lib/hw/memtrack.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/perfboost.default.so:system/lib/hw/perfboost.default.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/sensors.mt8127.so:system/lib/hw/sensors.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/hw/thermal.mt8127.so:system/lib/hw/thermal.mt8127.so \
    vendor/amazon/mt8127-common/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/amazon/mt8127-common/proprietary/lib/libGdmaScalerPipe.so:system/lib/libGdmaScalerPipe.so \
    vendor/amazon/mt8127-common/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/amazon/mt8127-common/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMPS.so:system/lib/libMPS.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMtkOmxAIVPlayer.so:system/lib/libMtkOmxAIVPlayer.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/amazon/mt8127-common/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/amazon/mt8127-common/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/amazon/mt8127-common/proprietary/lib/lib_uree_mtk_crypto.so:system/lib/lib_uree_mtk_crypto.so \
    vendor/amazon/mt8127-common/proprietary/lib/lib_uree_mtk_video_secure_al.so:system/lib/lib_uree_mtk_video_secure_al.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaal.so:system/lib/libaal.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/amazon/mt8127-common/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbessound_mtk.so:system/lib/libbessound_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/amazon/mt8127-common/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/amazon/mt8127-common/proprietary/lib/libblueshift-audioprocessing.so:system/lib/libblueshift-audioprocessing.so \
    vendor/amazon/mt8127-common/proprietary/lib/libblueshift-opus.so:system/lib/libblueshift-opus.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbluetooth_hw_test.so:system/lib/libbluetooth_hw_test.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/amazon/mt8127-common/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcameraanalyzer.so:system/lib/libcameraanalyzer.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/amazon/mt8127-common/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/amazon/mt8127-common/proprietary/lib/libdrmplayreadydecryptor.so:system/lib/libdrmplayreadydecryptor.so \
    vendor/amazon/mt8127-common/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/amazon/mt8127-common/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/amazon/mt8127-common/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/amazon/mt8127-common/proprietary/lib/libgsswrapper.so:system/lib/libgsswrapper.so \
    vendor/amazon/mt8127-common/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/amazon/mt8127-common/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/amazon/mt8127-common/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/amazon/mt8127-common/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/amazon/mt8127-common/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libiwnn.so:system/lib/libiwnn.so \
    vendor/amazon/mt8127-common/proprietary/lib/libiwnnaz.so:system/lib/libiwnnaz.so \
    vendor/amazon/mt8127-common/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmediacodeclogger.so:system/lib/libmediacodeclogger.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmediacodecloggerservice.so:system/lib/libmediacodecloggerservice.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmediaerrorlogger.so:system/lib/libmediaerrorlogger.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmongoose.so:system/lib/libmongoose.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmp2dec_sb.ca7.so:system/lib/libmp2dec_sb.ca7.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmtk_mali_user.so:system/lib/libmtk_mali_user.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/amazon/mt8127-common/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/amazon/mt8127-common/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/amazon/mt8127-common/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/amazon/mt8127-common/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/amazon/mt8127-common/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/amazon/mt8127-common/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/amazon/mt8127-common/proprietary/lib/libplayready.so:system/lib/libplayready.so \
    vendor/amazon/mt8127-common/proprietary/lib/libsmartsuspendmanagerservice.so:system/lib/libsmartsuspendmanagerservice.so \
    vendor/amazon/mt8127-common/proprietary/lib/libsmartvolume.so:system/lib/libsmartvolume.so \
    vendor/amazon/mt8127-common/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/amazon/mt8127-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/amazon/mt8127-common/proprietary/lib/libstlport.so:system/lib/libstlport.so \
    vendor/amazon/mt8127-common/proprietary/lib/libthermalservice.so:system/lib/libthermalservice.so \
    vendor/amazon/mt8127-common/proprietary/lib/libtoe.so:system/lib/libtoe.so \
    vendor/amazon/mt8127-common/proprietary/lib/libtrapz.so:system/lib/libtrapz.so \
    vendor/amazon/mt8127-common/proprietary/lib/libtz_uree.so:system/lib/libtz_uree.so \
    vendor/amazon/mt8127-common/proprietary/lib/liburee_meta_drmkeyinstall_v2.so:system/lib/liburee_meta_drmkeyinstall_v2.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/amazon/mt8127-common/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/amazon/mt8127-common/proprietary/lib/modules/ufsd.ko:system/lib/modules/ufsd.ko \
    vendor/amazon/mt8127-common/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/amazon/mt8127-common/proprietary/vendor/etc/audio_policy.conf:system/vendor/etc/audio_policy.conf \
    vendor/amazon/mt8127-common/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/amazon/mt8127-common/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/amazon/mt8127-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/amazon/mt8127-common/proprietary/xbin/chkexfat:system/xbin/chkexfat \
    vendor/amazon/mt8127-common/proprietary/xbin/chkufsd:system/xbin/chkufsd \
    vendor/amazon/mt8127-common/proprietary/xbin/memalloc:system/xbin/memalloc \
    vendor/amazon/mt8127-common/proprietary/xbin/mkexfat:system/xbin/mkexfat \
    vendor/amazon/mt8127-common/proprietary/xbin/start-ufsd:system/xbin/start-ufsd

PRODUCT_PACKAGES += \
    libMtkOmxVenc \
    libdpframework
